name: mealci
description: "Mealci App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  circle_nav_bar: ^2.1.1
  flutter:
    sdk: flutter
  motion_tab_bar: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
