name: mealci
description: "Mealci App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  http: ^1.2.2
  motion_tab_bar: ^2.0.4
  flutter_scalable_ocr: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
