# .github/workflows/flutter-setup.yml
name: Flutter Setup
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
      - run: flutter config --no-cli-animations
      - run: flutter pub get